// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATdk2DYbHuJYmoscp4IIFw2uvL1r81Anc',
    appId: '1:808916156790:android:7e6e8b93e831c2ad527a57',
    messagingSenderId: '808916156790',
    projectId: 'ipoedge-app',
    storageBucket: 'ipoedge-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4KFpMfN2vrseO_OaAUR33dngaz89XXM',
    appId: '1:808916156790:web:c7552efdb7733ec4527a57',
    messagingSenderId: '808916156790',
    projectId: 'ipoedge-app',
    authDomain: 'ipoedge-app.firebaseapp.com',
    storageBucket: 'ipoedge-app.firebasestorage.app',
    measurementId: 'G-CDDP92ZC3J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGoq12r7y8oDKb13szGExlYASaUKQoB3E',
    appId: '1:808916156790:ios:e406cd25e726164b527a57',
    messagingSenderId: '808916156790',
    projectId: 'ipoedge-app',
    storageBucket: 'ipoedge-app.firebasestorage.app',
    iosBundleId: 'com.ipoedge.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGoq12r7y8oDKb13szGExlYASaUKQoB3E',
    appId: '1:808916156790:ios:330eed291f94b228527a57',
    messagingSenderId: '808916156790',
    projectId: 'ipoedge-app',
    storageBucket: 'ipoedge-app.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa4KFpMfN2vrseO_OaAUR33dngaz89XXM',
    appId: '1:808916156790:web:30734fd8e697ad9a527a57',
    messagingSenderId: '808916156790',
    projectId: 'ipoedge-app',
    authDomain: 'ipoedge-app.firebaseapp.com',
    storageBucket: 'ipoedge-app.firebasestorage.app',
    measurementId: 'G-1P3ME45QG9',
  );

}